codec_encoder:
  ngf: 48
  hidden_dim: 1024
  depth: 1
  heads: 16
  pos_meb_dim: 64 
  up_ratios: [2, 2, 4, 4, 5]
  dilations: [1, 3, 9]

codec_decoder:
  ngf: 48
  up_ratios: [5, 4, 4, 2, 2] # [2, 5, 5, 4]
  dilations: [1, 3, 9]
  hidden_dim: 1024
  depth: 12
  heads: 16
  pos_meb_dim: 64 
  vq_num_quantizers: 1
  vq_dim: 2048 #1024 2048
  vq_commit_weight: 0.25
  vq_weight_init: False
  vq_full_commit_loss: False
  codebook_size: 16384  #8192 16384
  codebook_dim: 16

mpd:
  periods: [2, 3, 5, 7, 11]
  max_downsample_channels: 512
  channels: 16
  channel_increasing_factor: 4

mstft:
  stft_params:
    fft_sizes: [78, 126, 206, 334, 542,876,1418,2296]
    hop_sizes: [39, 63, 103, 167, 271,438,709,1148]
    win_lengths: [78, 126, 206, 334, 542,876,1418,2296]
    window: hann_window
  in_channels: 1
  out_channels: 1
  kernel_sizes: [5, 3]
  channels: 32
  max_downsample_channels: 512
  downsample_scales: [2, 2, 2]
  use_weight_norm: True
