defaults:
  - preprocess: default
  - dataset: default
  - model: default
  - train: default
log_dir: /aifs4su/data/zheny/bigcodec_final/logs_1020/v10_31
debug: false
ckpt: null # infer
input_dir: null # infer
output_dir: null # infer
hydra:
  output_subdir: hydra
  job:
    chdir: True
